### ISSUE TITLE
Azul ignores keyboard layout

### ISSUE THREAD

**Issue by o01eg** [maps4print/azul#37] opened 2018-10-30 14:45 UTC
## Description
When I launch text_input example and switch keyboard to Russian I still get symbols from English layout.

## Version / OS

* azul version: 71286f2 

* Operating system: Windows

## Steps to Reproduce
* Enable Russian keys
* Launch text_input example
* Switch layout to Russian
* Try to enter some symbols.

## Expected Behavior
Symbols from Russian layout appears.

## Actual Behavior
Symbols from English layout appears.

**Comment by fschutt** [comment] 2018-10-30 15:06
Yeah, winit doesn't have much support for non-English characters, see https://docs.rs/winit/0.17.2/winit/enum.VirtualKeyCode.html - that's all I have. There are other `VirtualKeyCode`s, but for some reason they are not exposed in the API.

**Comment by kyrias** [comment] 2018-10-30 15:18
I've been meaning to open essentially this issue for a while, because it's effectively blocking any use of Azul that I could have.

The problem is ultimately that Azul is currently just associating the raw virtual key codes with a static set of characters, which means that both different keyboard layouts and especially things like XCompose, which I *need* support for, fundamentally cannot work.  This is why any framework like this really need to integrate with the platform's native text input systems.

**Comment by fschutt** [comment] 2018-10-30 15:26
Yeah, the question is just how... technically it's the job of the operating system to care about managing keyboard layouts, so there should be a way to get the translated key. The question is just how this could be integrated - with or without winit. I am open for suggestions on that topic.

**Comment by kyrias** [comment] 2018-10-30 15:54
Looking through the winit/glium docs, the `WindowEvent` enum has a `ReceivedCharacter` variant that has the proper character, so that's what should be used for input characters really, and then the `KeyboardInput` one for things like the arrow keys which don't generate a `ReceivedCharacter`.   Hmm.

**Comment by fschutt** [comment] 2018-10-30 16:34
Ah yeah, I forgot that `ReceivedCharacter` was a thing. That could of course be an option, so I don't have to use the `VirtualKeyCode` to the the character from the OS. I'll look into using that later, I originally ignored it because it can be that winit sends characters twice (once as a `VirtualKeyCode` and once as a `ReceivedCharacter`).

**Comment by kyrias** [comment] 2018-10-30 17:09
Looking at the with bugtracker it seems that being able to associate a `ReceivedCharacter` with a `KeyboardEvent` wasn't added because it's apparently not possible to associate them on Windows.

On X &co both of them are generated from the same event, but on Windows they come in on separate event.

I can't really think of any way to easily reconcile those differences.

I wonder how other GUI frameworks handle this.

**Comment by kyrias** [comment] 2018-10-31 08:45
Read about this a bit more, and it seems that on Windows the way it works is that on any key press there's a `WM_KEYDOWN`, then a corresponding `WM_KEYUP` when it's released.  In the internal handling of the `WM_KEYDOWN`, if the keys correspond to a character, a `WM_CHAR` is generated.

So for example (example stolen from [here](https://www-user.tu-chemnitz.de/~heha/petzold/ch06d.htm)), if you hit `SHIFT` and then `A`, you get the following events:

```
WM_KEYDOWN | Virtual key code VK_SHIFT (0x10)
WM_KEYDOWN | Virtual key code for `A' (0x41)
WM_CHAR    | Character code for `A' (0x41)
WM_KEYUP   | Virtual key code for `A' (0x41)
WM_KEYUP   | Virtual key code VK_SHIFT (0x10)
```

So to handle this properly, I think we would need to keep track of the "nested" `WM_KEYDOWN` events, and if there's a `WM_CHAR` sandwiched between a group of `WM_KEYDOWN` and `WM_KEYUP` events we need to handle the `WM_CHAR` and probably just ignore the `WM_KEYDOWN` events.

**Comment by fschutt** [comment] 2018-11-02 11:42
Yes, this is probably all because I'm ignoring `ReceivedCharacter` for now, which does this translation. Should be fixed in the next few days.

**Closed** 2018-11-19 16:58 UTC
Labels: bug
