### ISSUE TITLE
Use vcpkg to build harfbuzz in Windows

### ISSUE THREAD

**Issue by yorodm** [maps4print/azul#170] opened 2019-05-10 21:10 UTC
## Description
Compiling harfbuzz-sys fails with the following
```
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.
```
## Describe your solution

Use vcpkg instead of cmake,  there's a harfbuzz package 

## Are there alternatives or drawbacks?

I think vcpkg is pretty much the way to go in Windows builds

## Is this a breaking change

Yes

**Comment by fschutt** [comment] 2019-05-11 12:16
No:

- This is easily solvable by just updating the cmake packages (see https://github.com/maps4print/azul/issues/163#issuecomment-489476077)
- This will break any cross-platform-ness, vcpkg does not work on Linux or Mac
- There is no integration of vcpkg with cargo (as there is with cmake), so `cargo build` would be impossible

Closing as duplicate of #163

**Closed by fschutt** 2019-05-11 12:16 UTC
Labels: feature-request

**Comment by yorodm** [comment] 2019-05-11 17:10
Counterpoints:

- `vcpkg` already knows how to find all kinds of Visual Studios.

- It is possible to use `vcpkg` as an alternative in `msvc` builds without breaking portability.

- There's [this vcpkg crate](https://docs.rs/vcpkg) and it seems to be widely used.
