### ISSUE TITLE
Empty component for Label and Button

### ISSUE THREAD

**Issue by t-shin-komae** [maps4print/azul#92] opened 2019-01-13 03:57 UTC
Hello

When I tried to execute "Hello World" in your README.md, this program shows empty Label and Button as below.

![screenshot from 2019-01-13 12-44-06](https://user-images.githubusercontent.com/44077048/51081350-f4890400-1730-11e9-9217-9d6441853df9.png)

OS:Ubuntu 18.04.1 LTS
Desktop enviroment: gnome-xorg
rustc: 1.31.1 (b6c32da9b 2018-12-18)
Cargo.toml
 [dependencies]
azul = { git = "https://github.com/maps4print/azul"}

The same code works on Windows 10.

**Comment by fschutt** [comment] 2019-01-13 04:33
This is basically the same issue as #65, so I'm closing this in favor of that issue. The reason this happens is because the fonts aren't loading in time for the first frame, they only load for the second frame. 

The font-loading infrastructure is currently changing, see the branch [refactor_dom](https://github.com/maps4print/azul/tree/refactor_dom). This is also why #78 (which fixes this bug temporarily) hasn't been merged yet.

If they still don't load after a resize or a click, then please reopen it as it's a different bug.

**Comment by t-shin-komae** [comment] 2019-01-13 06:55
Not only the first frame.
When I push the empty button, update_counter and layout function was called(I checked with println! macro), but the label and button does't changed.
And resizing doesn't help either.

**Comment by fschutt** [comment] 2019-01-13 07:51
Okay, then you probably don't have the correct fonts installed on your computer (this happened before). The problem is that currently azul uses fontconfig for determining the "native" font, which on many distributions, is not used by applications and therefore simply broken in many cases.

A possible workaround that would help a lot is to use gsettings to determine the "native" font instead, similar to the solution for the HiDPI factor. I'll reopen this, because it's a different bug.

**Comment by fschutt** [comment] 2019-01-14 09:50
A question - is it possible that your systems default font is in an OTF format (instead of TTF)? Azul can currently only load TTF fonts (a restriction of rusttype).

**Comment by fschutt** [comment] 2019-03-20 21:31
The problem itself should be fixed now, since Azul now uses FreeType and HarfBuzz, which can load OTF and font collection files - however, for some reason I've experienced that on Linux HarfBuzz simply only returns glyphs as spaces - so while the original reason for this issue is fixed, the result is probably still the same. Just wanted to give an update.

**Comment by fschutt** [comment] 2019-04-03 05:35
This should now be fixed (fixed in https://github.com/maps4print/azul/commit/87f3fb2dfd5c3976a284ebb06c8ced6217e0950b).

**Closed by fschutt** 2019-04-03 05:35 UTC
Labels: area:fonts, bug
