### ISSUE TITLE
UI doesn't render correctly under a tiling wm

### ISSUE THREAD

**Issue by zethra** [maps4print/azul#48] opened 2018-11-09 00:55 UTC
## Description
When a program using azul is launch under a tiling window manager in titling mode the ui doesn't render correctly.  Switching to floating mode and resizing the window doesn't fix the problem.  It seems like the rendering engine thinks the window is a different size than it is.

## Version / OS

* azul version:
87fc38ae66c482ead24c8cc1b5d4f6e082b6dfb8

* Operating system:
Ubuntu 16.04 running bspwm as the window manager

* Windowing system (X11 or Wayland, Linux only):
X11

## Steps to Reproduce
Run a azul example under a tiling wm

## Expected Behavior
![azul_working](https://user-images.githubusercontent.com/6034238/48236433-2cba4200-e390-11e8-982e-710a3269d1d2.png)

## Actual Behavior
![azul](https://user-images.githubusercontent.com/6034238/48236310-ad2c7300-e38f-11e8-96df-0b1d9fdd81bc.png)

**Comment by fschutt** [comment] 2018-11-09 01:03
This might be a bug in winit (the windowing toolkit that azul uses), not azul itself. I have heard reports of Wayland doing this, but none of X11. Are you on a 4k / HiDPI screen by any chance?

**Comment by Laaas** [comment] 2018-11-09 08:17
I have similar bugs under sway rev. 5c6240a9. It is probably a winit bug, since the wayland support under winit is quite incomplete. Setting the `WINIT_UNIX_BACKEND` environment variable to `x11` fixes this issue completely.

**Comment by fschutt** [comment] 2019-03-21 03:43
This bug itself should be fixed (probably same cause as #39). However, currently the window on wayland doesn't show so right now you'll probably not see a window on the screen, which is why I'm not closing this bug yet. Just wanted to give an update.

**Comment by zethra** [comment] 2019-03-21 03:55
Thanks for the update.  Unfortunate I don't use a tiling wm any more so I can't test this.

**Comment by X-m7** [comment] 2019-04-07 04:57
It seems to work fine on dwm now, though there's a white bar at the bottom for some reason, not sure if that's related.
![Screenshot_20190407_145247](https://user-images.githubusercontent.com/18729369/55678923-6003fb80-5945-11e9-8fe2-c23fdd8f43bb.png)
![Screenshot_20190407_145239](https://user-images.githubusercontent.com/18729369/55678924-685c3680-5945-11e9-9155-5201d5db37b8.png)

**Comment by fschutt** [comment] 2019-04-07 15:50
Yeah, the white line shows up on all platforms, that's a different bug (related to the layout system, not platform-specific). I've noticed it under Windows, too. Yes, the buttons don't resize vertically because they have a fixed height, that's not a bug.

I'm considering this bug to be resolved, since it seems to now show up correctly.

**Closed by fschutt** 2019-04-07 15:50 UTC
Labels: bug, platform:linux
