### ISSUE TITLE
Font on Button does not show if DOM contains a TextInput and a Button

### ISSUE THREAD

**Issue by nicohman** [maps4print/azul#66] opened 2018-11-27 18:56 UTC
## Description
Hi! I'm trying to create a basic text-based form, but whenever I add both the button to submit and the textinput to the dom, only the textinput works. The buttons become unstyled and don't respond to clicks. Am I just doing something wrong, or is this a bug?

## Version / OS

* azul version: 0.1.0

* Operating system: Arch Linux

* Windowing system (X11 or Wayland, Linux only): X11

## Steps to Reproduce
Have both a textinput and a button in the same div

## Expected Behavior
The both work the same way as they would independently

## Actual Behavior
The buttons become unstyled and fail to respond

## Additional Information

![2018-11-27-105052_980x619_scrot](https://user-images.githubusercontent.com/3522549/49104534-0f5ff180-f233-11e8-8922-5868eb9cf392.png)

**Comment by fschutt** [comment] 2018-11-28 00:50
From your screenshot alone, I can't really see what's going on - it's probably a styling bug, but I'm not sure. It does work fine for me:

![image](https://user-images.githubusercontent.com/12084016/49120257-34dd1180-f2ac-11e8-8933-7c9af48fa94c.png)

```rust
extern crate azul;

use azul::{prelude::*, widgets::{text_input::*, label::Label, button::Button}};

#[derive(Default)]
struct DataModel {
    counter: usize,
    text_input: TextInputState,
}

impl Layout for DataModel {
    fn layout(&self, info: WindowInfo<Self>) -> Dom<Self> {
        let label = Label::new(format!("{}", self.counter)).dom();
        let button =
            Dom::new(NodeType::Div)
                .with_child(Button::with_label("Update counter").dom().with_callback(On::MouseUp, Callback(update_counter)))
                .with_child(TextInput::new().bind(info.window, &self.text_input, &self).dom(&self.text_input));

        Dom::new(NodeType::Div)
            .with_child(label)
            .with_child(button)
    }
}

fn update_counter(app_state: &mut AppState<DataModel>, _event: WindowEvent<DataModel>) -> UpdateScreen {
    app_state.data.modify(|state| state.counter += 1);
    UpdateScreen::Redraw
}

fn main() {
    let app = App::new(DataModel::default(), AppConfig::default());
    app.run(Window::new(WindowCreateOptions::default(), Css::native()).unwrap()).unwrap();
}
```

For the styling - what does your CSS and your DOM look like? You can "dump" the DOM to a textual form using [debug_dump()](https://github.com/maps4print/azul/blob/2068541297c8345b622a8a05c5e0ac690d1c154e/src/dom.rs#L899)  - which just prints the hierarchical structure and IDs / classes, so I know the hierarchy of your layout.

```
0: [div  ]
     |-- 1: [div  .__azul-native-label]
     |       |-- 2: [p  ]
     |-- 3: [div  ]
     |       |-- 4: [div  .__azul-native-button]
     |       |       |-- 5: [p  ]
     |       |-- 6: [div  .__azul-native-input-text]
     |       |       |-- 7: [p  .__azul-native-input-text-label]
```

For now, make sure you are using only classes and IDs in your CSS. Other selectors are not properly done yet. By "failing to respond", you mean they don't execute the callbacks when you click on them? `:hover` attributes don't work yet. Technically, as long as you can see and click on a rectangle, you should always be able to at least invoke the callback attached to that rectangle.

So to debug this:

- Print the DOM (use the latest master, I fixed a small bug with printing) or post your`layout()` function, so I know at least roughly what your hierarchical structure looks like
- Try to give your buttons IDs and see if you can style them via IDs directly.
- Make sure you have the callbacks attached to the buttons using `On::MouseUp`

I am pretty sure that this is a bug, but from the information given I sadly can't reproduce it.

**Comment by r-arias** [comment] 2018-12-01 00:55
@fschutt if I copy and paste your example code given in this thread on Linux Ubuntu 16.04 with the current azul v0.1.0 (https://github.com/maps4print/azul#d75f2167) I have the same/a similar problem:
![screenshot from 2018-12-01 01-50-20](https://user-images.githubusercontent.com/6942802/49322018-761b2e80-f503-11e8-9ff0-5691a79a21fb.png)

The button works but the text does not render.

**Comment by fschutt** [comment] 2018-12-01 03:16
As I suspected, this was because of the recently-merged scrolling / overflow detection. https://github.com/maps4print/azul/commit/24998902b090617b7f0f9fe532398b811720c694 should temporarily fix this (these "weird" issues are likely due to buggy text overflow detection). However, this also disables scrolling (i.e the scroll_list example won't work anymore) - however, that's better than having the master branch being in a completely broken state.

**Comment by r-arias** [comment] 2018-12-01 07:53
Yep, I can confirm both your example above as well as my own code (that made me look for this issue) work as intended now, thanks!

**Comment by nicohman** [comment] 2018-12-02 00:06
Can also confirm that this works great now, thanks for your help!

**Comment by fschutt** [comment] 2019-04-04 08:07
I am closing this issue because the overflow / scrolling (which caused this bug) turned out to be far more complex than I initially thought, so scrolling will probably be a part of the 0.2 release, not the 0.1 - this bug is technically "fixed", but the downside is that scrolling doesn't work at all, but that's probably fine for now. For the 0.1 release, scrolling should be only available for iframes, in which case this bug will likely not happen anymore.

**Closed by fschutt** 2019-04-04 08:07 UTC
