### ISSUE TITLE
layout() fn continuously firing

### ISSUE THREAD

**Issue by kurtlawrence** [maps4print/azul#118] opened 2019-03-12 08:06 UTC
## Description

The layout() function is continuously being called which is degrading performance.

## Version / OS

* azul version: master branch

* Operating system: Windows

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce

Tried with a barebones implementation.
`called layout()` will be continuously printed.

```rust
extern crate azul;
use azul::prelude::*;

struct MyApp;

impl Layout for MyApp {
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        println!("called layout()",);

        Dom::label("hello")
    }
}

fn main() {
    let app = App::new(MyApp, AppConfig::default());

    let window = Window::new(WindowCreateOptions::default(), css::native()).unwrap();

    app.run(window).unwrap();
}
```

## Additional Information

I was under the impression that layout calls were only made if necessary (with `Redraw` or resizing etc). I might be mistaken.

**Comment by fschutt** [comment] 2019-03-12 19:58
Yes, this is currently only a problem on the master branch. You can roll back to https://github.com/maps4print/azul/commit/87d85a70176a8b0e6cbd516f7cb246238c371611, where this problem is fixed or use the `positioned_words` branch where it's also already fixed. Calling layout() again is technically by design, however it should of course only be called when something has changed.

**Comment by fschutt** [comment] 2019-03-21 01:34
This is fixed now, although the current calls to layout() might be too conservative (i.e. the window only gets redrawn on user input, which leads to a few problems with resizing).

**Closed by fschutt** 2019-03-21 01:34 UTC
Labels: bug
