### ISSUE TITLE
Flickering after changing pages

### ISSUE THREAD

**Issue by Weasy666** [maps4print/azul#76] opened 2018-12-10 20:07 UTC
## Description
When changing/swapping the rendered content of a page there is some kind of flicker/after-image of the previously rendered page.

## Version / OS
* azul version: cb2702b

* Operating system: Windows 10 1809

* rust toolchain:
  * nightly-x86_64-pc-windows-msvc (default)  
  * rustc 1.32.0-nightly (14997d56a 2018-12-05)

## Steps to Reproduce
Use the code from [here](https://github.com/maps4print/azul/issues/60#issuecomment-440030643) and implement two different pages and navigate between them with a callback on a button.

## Expected Behavior
Different pages render without flickering.

## Actual Behavior
See GIF below.

## Additional Information
![poomxyryltfbdxel04tpnikhjb8psh14wx4xu8kq](https://user-images.githubusercontent.com/11967542/49758195-aa8aa980-fcbe-11e8-8b00-51e0360af2a2.gif)

**Comment by Weasy666** [comment] 2018-12-10 20:35
Yeah, initially i ran it in debug. But after switching to `cargo build --release` it still flickers, not as much as before, but it is still there.

**Comment by fschutt** [comment] 2018-12-10 20:44
Oh, well in that case, it's probably a bug. But I noticed that you use a pretty old version of azul, like 1 month old, could you try it again with the current master?

**Comment by Weasy666** [comment] 2018-12-10 20:45
Ah...sorry. That was a copy paste error. I'm currently using cb2702b.

**Comment by lodsb** [comment] 2018-12-21 21:32
Maybe this issue is related to my experience ( @ f9d2ce4 ): most example apps start without properly rendered text; forcing a redraw by resizing the window will then show the text. Superficially (without investigation/looking into the code), the flickering seems to be caused by alternating between UI states, e.g. take a look at the screen-capture of the game of life app: https://drive.google.com/open?id=1EzSOue1VesRrfFvb-aNK6qCtU_Tkmb_v (it is also a bit odd that the app uses one core at near 100%).

**Comment by antonok-edm** [comment] 2018-12-23 05:09
@lodsb I worked on fixing the issue where apps start without text in #78. It's not merged, but you could try using my master branch at https://antonok-edm/azul and see if it makes any difference. I haven't personally been able to reproduce the flickering, so I can't tell for myself, but my hunch from how the code is structured is that it's a separate issue.

**Comment by fschutt** [comment] 2018-12-23 06:39
@antonok-edm yeah, I have been working on the font changes on a seperate branch, see https://github.com/maps4print/azul/tree/font_refactoring - not working yet, but it has a way better structure than the old display list code.

I know about the flickering, I could reproduce it, but to me it's not such a big issue right now for me (i.e. I can still use apps that flicker, even though it's a shit UX), so I've put it as a lower priority on the list. If anyone knows the cause of this problem, that would probably help more than making commits that "hope to fix it".

**Comment by lodsb** [comment] 2018-12-25 14:04
Ok, thanks for the heads up! I tried antonok's master branch and it seems to flicker less, the missing initial font rendering is still there. But I agree that there may be more pressing issues right now.

**Closed** 2019-02-17 20:19 UTC

**Comment by fschutt** [comment] 2019-02-17 20:25
So, investigating this bug, it seems that this was caused because the display got swapped two times - once by the `force_redraw_cache` (which was done to work around redrawing bugs in winit) and once when receiving a `should_swap_window` event (which is generated by the OS, not under azuls control). Because the OS didn't know about the `force_redraw_cache`, workaround, the window would swap twice.

Now the `should_swap_window` event from the OS is getting ignored (the implementation is also fairly inconsistent between OS), and completely replaced by `force_redraw_cache`, so there shouldn't be any flickering bugs anymore.

Also fixed that GL textures would never get cleaned up because `if usize == 0 { }` is always false, so that's better now.
