### ISSUE TITLE
Newline in xml text causes formatting errors

### ISSUE THREAD

**Issue by gmorenz** [maps4print/azul#113] opened 2019-02-17 04:36 UTC
## Description

For example, in the xml example, changing `You can hot-reload this UI, see /examples/ui.xml` to

```
You can hot-reload this UI, 
see /examples/ui.xml
```

results in the screenshots below

## Version / OS

* azul version: e6dfa134
* Operating system: Linux
* Windowing system (X11 or Wayland, Linux only): X11

## Steps to Reproduce

See description

## Additional Information

Before adding newline:

![image](https://user-images.githubusercontent.com/595972/52908410-8bbb0d00-3243-11e9-8e0e-3d95a80fda2a.png)

After adding newline:

![image](https://user-images.githubusercontent.com/595972/52908416-9d9cb000-3243-11e9-853b-27787f929ad1.png)

**Comment by fschutt** [comment] 2019-02-17 15:21
I know, it has to do with the newline. This is also the cause for #101 (but a different aspect of the same bug) - for some reason the newline is treated differently during the text layout.

**Comment by fschutt** [comment] 2019-02-18 17:20
The first problem is that the height of the text (without newlines) isn't calculated correctly because the current algorithm just counts the number of `\n` characters and multiplies that by the number of return characters. Since the number of newlines is 0, the height of the text was 0, which is why a text with no newlines displays differently.

The second bug is that the height of the text with newlines gets calculated incorrectly because the text layout doesn't take automatic line breaking at the text bounding box into account. You can see this in the second screenshot where the second line of text is cut off.

The third bug (which causes the layout to change) is that if the text has a height of more than 0, then the layout algorithm treats it as if this height is the definite, final height of the div - this was originally done for layouting images, so that they don't get distorted - the height of the image is also the final height of the div. However, this is the wrong behaviour, as the height of images and text do not have to be the height of the final element.

Right now, all UIs are broken and look like the second screenshot because I've fixed #101 - sorry about that, but at least it's progress. This issue has very high priority because I just broke my own UIs, but it should be fixed soon.

**Comment by fschutt** [comment] 2019-03-20 21:18
This is fixed since https://github.com/maps4print/azul/commit/efaedc0790d761720ff3a7b89775a5c023a95652 - I reworked the text layout system (although it's still not perfect).

**Closed by fschutt** 2019-03-20 21:18 UTC
Labels: area:layout, bug
