### ISSUE TITLE
CSS setting border-top to none removes all borders

### ISSUE THREAD

**Issue by cubetastic33** [maps4print/azul#144] opened 2019-04-08 17:28 UTC
## Description
The `border-top` CSS property when set to none removes all the borders that were set for that element

## Version / OS

* azul version:
e805c1c0372c7b73f14306d4ae33b00dbc107ba3

* Operating system:
Arch Linux

* Windowing system (X11 or Wayland, Linux only):
X11

## Steps to Reproduce
+ Set the `border` property of an element, like `border: 1px solid black;`
+ Set the `border-top` property of an element to none, like `border-top: none;`
+ All the borders disappear
+ Setting the `border-right`, `border-bottom`, and `border-left`properties explicitly to `1px solid black;` after the `border-top: none;` also gives the same result

**Comment by mjhouse** [comment] 2019-04-12 02:09
I looked into this today, and before the following block of code, there are multiple BorderStyle elements in a CssRuleBlock in the css struct, afterward only the last style exists. I think the first BorderStyle gets overwritten by the latest. How this works when you're explicitly setting the `border-top`/`border-right` properties etc. I'm not sure. 

Maybe each new border property is overwriting the previous one, and there is another bug related to displaying a single border. I did notice, when I reproduced this, that there were small black corners on the div, even though there were no borders visible. May have something to do with the radius property.

I'll try and work on this more at some point.

**note**: azul-css-parser/css.rs:471 Is where CssRuleBlock are collected for first time (css_blocks)

-------------------------------------------------------------------------------------------------------------------
style.rs: 389 - 395
-------------------------------------------------------------------------------------------------------------------
    let mut styled_nodes = ui_state.dom.arena.node_data.transform(|_, node_id| StyledNode {
        css_constraints: css
            .rules()
            .filter(|rule| matches_html_element(&rule.path, node_id, &ui_state.dom.arena.node_layout, &html_tree))
            .flat_map(|matched_rule| matched_rule.declarations.iter().map(|declaration| (declaration.get_type(), declaration.clone())))
            .collect(),
    });
-------------------------------------------------------------------------------------------------------------------


BEFORE ------------------------------------------------------------------------------------------------------------

    path: #text_input_1,
    declarations: [
        ...
        Static(
            Border(
                StyleBorder {
                    top: Some(
                        StyleBorderSide {
                            border_width: 2px,
                            border_style: Solid,
                            border_color: ColorU {
                                r: 0,
                                g: 0,
                                b: 0,
                                a: 255
                            }
                        }
                    ),
                    left: Some(
                        StyleBorderSide {
                            border_width: 2px,
                            border_style: Solid,
                            border_color: ColorU {
                                r: 0,
                                g: 0,
                                b: 0,
                                a: 255
                            }
                        }
                    ),
                    bottom: Some(
                        StyleBorderSide {
                            border_width: 2px,
                            border_style: Solid,
                            border_color: ColorU {
                                r: 0,
                                g: 0,
                                b: 0,
                                a: 255
                            }
                        }
                    ),
                    right: Some(
                        StyleBorderSide {
                            border_width: 2px,
                            border_style: Solid,
                            border_color: ColorU {
                                r: 0,
                                g: 0,
                                b: 0,
                                a: 255
                            }
                        }
                    )
                }
            )
        ),
        Static(
            Border(
                StyleBorder {
                    top: Some(
                        StyleBorderSide {
                            border_width: 3px,
                            border_style: None,
                            border_color: ColorU {
                                r: 0,
                                g: 0,
                                b: 0,
                                a: 255
                            }
                        }
                    ),
                    left: None,
                    bottom: None,
                    right: None
                }
            )
        ),
        ...
    ]

AFTER  ------------------------------------------------------------------------------------------------------------

    [azul\src\style.rs:397] &styled_nodes = NodeDataContainer {
        internal: [
            StyledNode {
                css_constraints: {
                    ...
                    Border: Static(
                        Border(
                            StyleBorder {
                                top: Some(
                                    StyleBorderSide {
                                        border_width: 3px,
                                        border_style: None,
                                        border_color: ColorU {
                                            r: 0,
                                            g: 0,
                                            b: 0,
                                            a: 255
                                        }
                                    }
                                ),
                                left: None,
                                bottom: None,
                                right: None
                            }
                        )
                    )
                }
            },
            ...
        ]
    }

**Comment by fschutt** [comment] 2019-04-12 02:41
No, that's not how it works (at least not intentionally), look at the `parse_tblr` (top-bottom-left-right) macro. Basically, within a CSS "block", there is only one border declaration, and the latter declarations overwrite the previous ones:

```css
#thing {
    border: 10px solid black;
    border-bottom: 2px dotted red;
}
```
... get expanded to:

```css
#thing {
    border-top: 10px solid black;
    border-bottom: 10px solid black;
    border-left: 10px solid black;
    border-right: 10px solid black;
    border-bottom: 2px dotted red;
}
```
... and then reduced to:

```css
#thing {
    border-top: 10px solid black;
    border-bottom: 2px dotted red; // overwrites earlier border-bottom, order important
    border-left: 10px solid black;
    border-right: 10px solid black;
}
```

The CSS cascading logic is then done later. The problem is in the css_parser.rs, not the styling module, you're looking at the wrong place.

**Comment by mjhouse** [comment] 2019-04-12 10:03
I saw that, but I didn't see how the result of a later call to `parse_key_value_pair` could overwrite the top/bottom/left/right of a previous result. It creates a StyleBorder when the border property is set, and another one later for BorderTop:
![image](https://user-images.githubusercontent.com/4141157/56029379-dacf6c80-5cdf-11e9-911f-df7da06f5f36.png)

Where is it getting the first StyleBorder to overwrite it?

**Comment by fschutt** [comment] 2019-05-13 14:44
This issue is now solved (in the `gl_rework` branch), but isn't yet merged into master.

**Comment by fschutt** [comment] 2019-06-19 08:26
This is fixed now, although the master branch has different issues. Thanks for reporting.

**Closed by fschutt** 2019-06-19 08:26 UTC
Labels: bug
