### ISSUE TITLE
UI blank and renders only after resize/click

### ISSUE THREAD

**Issue by r-arias** [maps4print/azul#65] opened 2018-11-25 11:32 UTC
## Description

When trying out the examples on my machine, I noticed that reproducibly  the UI only shows after I force a redraw by resizing the window or clicking somewhere inside it.

## Version / OS

* azul version:
version = "0.1.0"
source = "git+https://github.com/maps4print/azul#2068541297c8345b622a8a05c5e0ac690d1c154e"

* Operating system:
Linux Ubuntu 16.04

* Windowing system (X11 or Wayland, Linux only):
X11

* Rust:
rustc 1.30.1 (1433507eb 2018-11-07)

## Steps to Reproduce

* Create a new cargo project with azul as dependency.
* paste one of the azul examples in main.rs
* `cargo run`

## Expected Behavior
The window opens and immediately shows the rendered example.

## Actual Behavior
The window is empty and only redraws the example when resizing the window or clicking somewhere.

![screenshot from 2018-11-25 12-25-03](https://user-images.githubusercontent.com/6942802/48978563-e4479780-f0a4-11e8-8b5b-6fee3b60a76c.png)

After clicking:
![screenshot from 2018-11-25 12-25-23](https://user-images.githubusercontent.com/6942802/48978571-0e00be80-f0a5-11e8-9897-3b5c350ddab5.png)

**Comment by nicohman** [comment] 2018-11-26 23:37
Just to chip in, I have also been experiencing this on Arch Linux under both xfce and i3, using the most recent version of azul. Thanks for taking a look at this!

**Comment by jqcorreia** [comment] 2018-11-29 18:32
I'm also having issues with this. The basic example from the tutorial renders both Label and Button but the text is missing and click 'animation' doesn't happen.

**Comment by fschutt** [comment] 2018-11-29 18:40
@jqcorreia Could you share a screenshot of what you mean? Does or doesn't it render the label? There is no animation yet (i.e. `:hover`) - did you mean that it doesn't increase the counter?

I know that this is a problem on windows, too, it appeared after the text layout de-duplication fix - the problem is more or less that the font gets loaded, but only gets rendered on the second frame, i.e. it gets uploaded, but not rendered in time for the first frame. For now, I considered it low-priority, since it only appears on startup and technically doesn't break the functionality of the app (and I don't have much time right now to investigate this).

**Comment by jqcorreia** [comment] 2018-11-29 18:54
Sure thing. BTW this is by far the only *sane* GUI framework that I came across during my yet short working time with Rust. Nice one.

DataModel looks like this:
```
impl Layout for MyDataModel {
    fn layout(&self, _: WindowInfo<Self>) -> Dom<Self> {
        println!("Running layout");
  
        let label = Label::new(format!("{}", 1000)).dom();
  
        Dom::new(NodeType::Div)
            .with_child(label)
    }
}
```

The result is this
![scrot](https://user-images.githubusercontent.com/2652464/49244470-c9a85200-f407-11e8-9088-fc7eca0799d8.jpg)

You can see there that I'm using a tiling WM, the 'Running Layout' is printed a couple of times and that the label contains no text. If I add a button as the Counter example the button outline shows but no text and on-click nothing happens besides another 'Running Layout' print.

**Comment by fschutt** [comment] 2018-11-30 22:12
No, there is very little you can do. This is an issue with azul, not your system. If you really wanted to debug this, you could debug where / if the text gets pushed in the display list, but that's maybe a bit too advanced.

**Comment by fschutt** [comment] 2018-12-13 20:08
Just tested it, it's not fixed yet, reopening.

**Comment by antonok-edm** [comment] 2018-12-13 20:21
@fschutt Strange, that definitely fixed it for me. Maybe this is somehow platform-dependent? 

@r-arias @nicohman @jqcorreia could any of you report your results on the latest version?

**Comment by antonok-edm** [comment] 2018-12-14 00:02
I did some more testing -- apparently, it works only on the calculator example, which is the only one I tried out!

The calculator example is the only one which loads an external font, and making it use the default font also causes the same issue. I will look into this some more. At least, for now, if you load in your own font it will work as expected.

**Comment by TheJare** [comment] 2018-12-14 23:02
The issue happens as described for me in Windows 10 with 64 bit msvc Rust. Window appears and the two rectangles for the label and the (gray background) button appear, but no visible text until I click on the button or resize the window.

Note that just clicking on the label does not make the text appear, only the actual button click.

**Comment by jordanbray** [comment] 2019-01-20 01:14
I can confirm this issue.  I can also confirm that manually loading a font (stole code from the calculator example per posts on this issue) resolves the issue.

**Comment by fschutt** [comment] 2019-03-20 21:38
This is fixed now with the new font loading system (see https://github.com/maps4print/azul/pull/78#issuecomment-475024482) - however there is currently the issue that Linux for some reason doesn't render fonts at all (I'm working on that). This bug in particular is solved, though.

**Closed by fschutt** 2019-03-20 21:38 UTC
Labels: area:fonts, bug
